- name: Hello World Sample
  hosts: all
  vars:

  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Print custom details
      debug:
        msg: "{{ sid }}"
        loop:
          - slack_channel: '{{ slack_channel  }}'
          - slack_token: '{{ slack_token }}'
        loop_control:
          loop_vars: sid

