- name: Hello World Sample
  hosts: all
  vars:
    slack_channel: '{{ slack_channel  }}'
    slack_token: '{{ slack_token }}'

  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Print custom details
      debug:
        msg: "{{ item }}"
      loop:
        - '{{ slack_channel  }}'
        - '{{ slack_token }}'

