- name: Hello World Sample
  hosts: localhost
  vars:
    channel: '{{channel}}'
    #slack_token: '{{ token }}'

  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Print custom details
      debug:
        msg: "{{channel}}"
      

